# Generated by Django 4.2.30 on 2026-06-21 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='número de orden')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='correo del cliente')),
                ('customer_name', models.CharField(max_length=200, verbose_name='nombre del cliente')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='teléfono del cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('confirmed', 'Confirmado'), ('dispatched', 'Despachado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, verbose_name='ID de mensaje WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pedido por WhatsApp',
                'verbose_name_plural': 'pedidos por WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(max_length=200, verbose_name='nombre del producto (snapshot)')),
                ('variant_snapshot', models.CharField(max_length=200, verbose_name='variante (snapshot)')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.whatsapporder', verbose_name='pedido')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'ítem de pedido',
                'verbose_name_plural': 'ítems de pedido',
                'ordering': ['-created_at'],
            },
        ),
    ]
