# Generated by Django 4.2.30 on 2026-06-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='código de cupón'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuento aplicado'),
        ),
    ]
