# Generated by Django 4.2.30 on 2026-06-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_whatsapporder_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='entregado en'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Ej: Transferencia, Contraentrega, Nequi', max_length=40, verbose_name='método de pago'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='despachado en'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='dirección de envío'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='shipping_carrier',
            field=models.CharField(blank=True, help_text='Ej: Servientrega, Coordinadora, Interrapidisimo', max_length=80, verbose_name='transportadora'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='ciudad de envío'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de envío'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='shipping_department',
            field=models.CharField(blank=True, max_length=120, verbose_name='departamento/estado de envío'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='shipping_notes',
            field=models.TextField(blank=True, help_text='Referencias, edificio, apartamento, etc.', verbose_name='notas de envío'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='número de guía'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de rastreo'),
        ),
        migrations.AlterField(
            model_name='whatsapporder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('confirmed', 'Confirmado'), ('dispatched', 'Despachado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado'),
        ),
    ]
