# Generated by Django 4.2.30 on 2026-06-22 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='suscrito en')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='desuscrito en')),
                ('source', models.CharField(blank=True, help_text='Cómo se suscribió (footer, registro, etc.)', max_length=50, verbose_name='origen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'suscriptor al newsletter',
                'verbose_name_plural': 'suscriptores al newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
