# Generated by Django 4.2.30 on 2026-06-21 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_number', models.CharField(max_length=30, verbose_name='número de WhatsApp')),
                ('whatsapp_message_template', models.TextField(default='Hola MARPLATA! Me interesa realizar un pedido. Mis datos son:\nNombre: {customer_name}\nCorreo: {customer_email}\nTeléfono: {customer_phone}\nProductos:\n{products}', verbose_name='plantilla de mensaje WhatsApp')),
                ('site_name', models.CharField(default='MARPLATA', max_length=100, verbose_name='nombre del sitio')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='costo de envío')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='umbral de envío gratis')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='DataConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('consented_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de consentimiento')),
                ('consent_version', models.CharField(max_length=20, verbose_name='versión de política')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de consentimiento',
                'verbose_name_plural': 'registros de consentimiento',
                'ordering': ['-consented_at'],
            },
        ),
    ]
