# Generated by Django 4.2.30 on 2026-06-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, verbose_name='dirección física'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='business_hours',
            field=models.CharField(blank=True, help_text='Ej: Lun-Vie 9am-6pm, Sáb 9am-1pm', max_length=200, verbose_name='horario de atención'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pinterest_url',
            field=models.URLField(blank=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_tagline',
            field=models.CharField(default='Diseña tu estilo, resalta tu esencia', max_length=200, verbose_name='eslogan'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(help_text='Incluir código de país, ej: +573001234567', max_length=30, verbose_name='número de WhatsApp'),
        ),
    ]
