# Generated by Django 4.2.30 on 2026-06-22 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_address_siteconfig_business_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(choices=[('nosotros', 'Nosotros'), ('contacto', 'Contacto'), ('envios-devoluciones', 'Envíos y devoluciones'), ('politica-privacidad', 'Política de privacidad'), ('terminos-condiciones', 'Términos y condiciones')], help_text='Identificador de la URL. Una vez creado, no se puede cambiar.', max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtítulo')),
                ('content', models.TextField(help_text='Contenido de la página. Soporta HTML básico.', verbose_name='contenido')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('show_in_footer', models.BooleanField(default=True, help_text='Si está activo, se muestra automáticamente en el footer.', verbose_name='mostrar en footer')),
                ('footer_section', models.CharField(blank=True, choices=[('', 'Sin sección específica'), ('navegacion', 'Navegación'), ('legal', 'Legal'), ('ayuda', 'Ayuda')], default='legal', max_length=50, verbose_name='sección del footer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta título')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['order', 'title'],
            },
        ),
    ]
