"""
Django settings for MARPLATA project.

Generated by Django 4.2 + Custom User Model.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-marplata-fase1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition
DJANGO_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.admin',
]

THIRD_PARTY_APPS = [
    'jazzmin',
]

LOCAL_APPS = [
    'apps.accounts',
    'apps.catalog',
    'apps.cart',
    'apps.orders',
    'apps.core',
]

INSTALLED_APPS = THIRD_PARTY_APPS + DJANGO_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Database (override in dev/prod)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Login/Logout redirects
LOGIN_URL = '/cuenta/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# WhatsApp business number for checkout (include country code, e.g. +573001234567)
MARPLATA_WHATSAPP_NUMBER = os.getenv('MARPLATA_WHATSAPP_NUMBER', '+573001234567')

# Site URL (used in email links, OG tags, etc.)
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

# Default email "from" address (overridden in dev/prod)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'MARPLATA <no-reply@marplata.com>')

# Password reset uses HTTPS links in production
if os.getenv('DEBUG', 'False').lower() not in ('true', '1', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Jazzmin configuration
JAZZMIN_SETTINGS = {
    "site_title": "MARPLATA Admin",
    "site_header": "MARPLATA",
    "site_brand": "MARPLATA",
    "site_logo": None,
    "welcome_sign": "Diseña tu estilo, resalta tu esencia.",
    "copyright": "MARPLATA",
    "search_model": ["accounts.CustomUser", "catalog.Product", "orders.WhatsAppOrder"],
    "user_avatar": None,
    "show_ui_builder": False,
    "show_sidebar": True,
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "Dashboard", "url": "/admin/dashboard/", "icon": "fas fa-chart-line"},
    ],
    "icons": {
        "accounts.CustomUser": "fas fa-user",
        "accounts.NewsletterSubscriber": "fas fa-envelope",
        "accounts.WishlistItem": "fas fa-heart",
        "auth.Group": "fas fa-users",
        "catalog.Collection": "fas fa-layer-group",
        "catalog.Product": "fas fa-tshirt",
        "catalog.ProductVariant": "fas fa-palette",
        "catalog.VariantImage": "fas fa-images",
        "catalog.Promotion": "fas fa-tags",
        "catalog.CouponRedemption": "fas fa-ticket-alt",
        "cart.Cart": "fas fa-shopping-basket",
        "cart.CartItem": "fas fa-list-ul",
        "orders.WhatsAppOrder": "fas fa-clipboard-check",
        "orders.WhatsAppOrderItem": "fas fa-box-open",
        "core.SiteConfig": "fas fa-cog",
        "core.DataConsentLog": "fas fa-shield-alt",
        "core.Page": "fas fa-file-alt",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent_active": "navbar-primary",
    "accent": "navbar-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
}
