# Generated by Django 4.2.30 on 2026-06-21 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'colección',
                'verbose_name_plural': 'colecciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='descripción')),
                ('story', models.TextField(blank=True, verbose_name='historia')),
                ('materials', models.CharField(blank=True, max_length=200, verbose_name='materiales')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio base')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta título')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.collection', verbose_name='colección')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('color_slug', models.SlugField(verbose_name='slug de color')),
                ('size', models.CharField(max_length=20, verbose_name='talla')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio especial')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'variante de producto',
                'verbose_name_plural': 'variantes de producto',
                'ordering': ['product', 'color', 'size'],
                'unique_together': {('product', 'color_slug', 'size')},
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/variants/', verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='imagen principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'imagen de variante',
                'verbose_name_plural': 'imágenes de variantes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=20, verbose_name='tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor de descuento')),
                ('start_date', models.DateTimeField(verbose_name='fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('applicable_collections', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.collection', verbose_name='colecciones aplicables')),
            ],
            options={
                'verbose_name': 'promoción',
                'verbose_name_plural': 'promociones',
                'ordering': ['-created_at'],
            },
        ),
    ]
