# Generated by Django 4.2.30 on 2026-06-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen principal que se muestra en catálogos y listados.', null=True, upload_to='products/covers/', verbose_name='imagen de portada'),
        ),
    ]
