# Generated by Django 4.2.30 on 2026-06-22 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_whatsapporder_coupon_code_and_more'),
        ('catalog', '0002_product_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='min_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo del carrito para que el cupón sea válido.', max_digits=10, null=True, verbose_name='compra mínima'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='usos realizados'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de veces que el cupón puede ser usado. Vacío = ilimitado.', null=True, verbose_name='límite de usos'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_used', models.CharField(max_length=50, verbose_name='código usado')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='descuento aplicado')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='canjeado en')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='orders.whatsapporder', verbose_name='orden')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='catalog.promotion', verbose_name='promoción')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'canje de cupón',
                'verbose_name_plural': 'canjes de cupón',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
