# Generated by Django 4.2.30 on 2026-06-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_promotion_min_purchase_promotion_usage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Se notificará cuando el stock sea igual o menor a este número.', verbose_name='umbral de stock bajo'),
        ),
    ]
