# Generated by Django 4.2.30 on 2026-07-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariant_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=4, verbose_name='talla'),
        ),
    ]
